Skip to content
sagit-battery-fix
Repository navigation
Code
Issues
Pull requests
Agents
Build Kernel
Build Kernel #2
Annotations
1 error and 1 warning
build
failed 21 minutes ago in 1m 16s
1s
1s
46s
0s
23s
3s
Run cd src
make[1]: Entering directory '/home/runner/work/sagit-battery-fix/sagit-battery-fix/src/out'
  HOSTCC  scripts/basic/fixdep
  GEN     ./Makefile
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/zconf.lex.c
  SHIPPED scripts/kconfig/zconf.hash.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
#
# configuration written to .config
#
make[1]: Leaving directory '/home/runner/work/sagit-battery-fix/sagit-battery-fix/src/out'
make[1]: Entering directory '/home/runner/work/sagit-battery-fix/sagit-battery-fix/src/out'
  GEN     ./Makefile
scripts/kconfig/conf  --silentoldconfig Kconfig
arch/arm64/Makefile:28: ld does not support --fix-cortex-a53-843419; kernel may be susceptible to erratum
arch/arm64/Makefile:68: *** CROSS_COMPILE_ARM32 not defined or empty, the compat vDSO will not be built.  Stop.
make[1]: Leaving directory '/home/runner/work/sagit-battery-fix/sagit-battery-fix/src/out'
make: *** [Makefile:152: sub-make] Error 2
Error: Process completed with exit code 2.
0s
0s
1s
